### ISSUE TITLE
Update from Grid to Interpolation

### ISSUE THREAD

**Issue by MC-Bourguiba** [JuliaMath/Interpolations.jl#209]
Hi,
I am pretty new to Julia., so in advance please excuse my ignorance. My issue I am facing is that I have a code which has been written in Julia 0.5 with the package Grid. I am trying to update some part of it using the Interpolations package.
I changed the following line:
`cost_table = InterpGrid(cost_table, BCnil, InterpLinear)`
to:
`cost_table = interpolate(cost_table,extrapolate(cost_table, Interpolations.Throw()), Linear)`

but got this error that I am unable to decipher 

`
ERROR: LoadError: MethodError: no method matching extrapolate(::Array{Float64,3}, ::Interpolations.Throw)
Closest candidates are:
extrapolate(::Interpolations.AbstractInterpolation{T,N,IT,GT}, ::ET<:Union{Interpolations.Flag, Tuple{Vararg{Union{Interpolations.Flag, Tuple{Interpolations.Flag,Interpolations.Flag}},N} where N}}) where {T, N, IT, GT, ET<:Union{Interpolations.Flag, Tuple{Vararg{Union{Interpolations.Flag, Tuple{Interpolations.Flag,Interpolations.Flag}},N} where N}}} at C:\Users\chedh\.julia\v0.6\Interpolations\src\extrapolation/extrapolation.jl:30
ERROR: syntax: extra token "at" after end of expression`

Thank you very much for your help!

**Comment by tlycken** [comment]
The error basically says that there is no method of `interpolate` that accepts arguments like the ones you provided - which makes sense, because it seems you're doing things a little backwards. The construction API is a little confusing at the moment, but I think there are plans to build convenience constructors that make it a littl easier.

It seems like what you want to do is this:

    using Interpolations
    itp = interpolate(cost_table, BSpline(Linear(), OnCell()) # Grid.jl didn't support OnGrid, so I'm assuming here
    etp = extrapolate(itp, Throw())

and then use `etp` for evaluating the interpolation. (In your sample you re-assign `cost_table`, which could have performance issues, so I created a new variable here.)
