### ISSUE TITLE
Spurious warning about concrete types

### ISSUE THREAD

**Issue by cstjean** [JuliaMath/Interpolations.jl#287]
I interpolate over arrays that contain `missing` values, and I get the following warning:
```julia
┌ Warning: For performance reasons, consider using an array of a concrete type (eltype(A) == Union{Missing, Float32})
└ @ Interpolations ~/.julia/packages/Interpolations/1CM1Q/src/gridded/gridded.jl
```
Now that small union types are efficiently represented, isn't it a bit outdated?

**Comment by timholy** [comment]
Yes, it's outdated. But it needs someone who uses `missing` values (I don't) to make the changes.

**Comment by tpapp** [comment]
Since which arrays are represented "efficiently" is something that is not part of the API and can change, and there is no API to query this for a given type, I wonder if the package should warn about this at all.

**Comment by cstjean** [comment]
Is there a special Interpolations.jl-specific concern about working with non-isbits arrays? Otherwise, the warning is just generic advice about good performance in Julia.

**Comment by timholy** [comment]
I'm utterly swamped right now but you could use `git blame` to trace the breadcrumbs on that warning.

Getting rid of the warning is presumably easy, but it might make sense to tackle #199 etc.

**Comment by tpapp** [comment]
> generic advice about good performance in Julia

Advice about performance is always nice, but detecting performance pitfalls is difficult and sometimes relies on internals or implicit assumptions, so for a package which is not explicitly for performance tuning (like eg [TraceCalls.jl](https://github.com/cstjean/TraceCalls.jl)) it may just be an extra maintenance burden with false positives/negatives, as this issue demonstrates.

**Comment by cstjean** [comment]
The warning came with the initial PR that created gridded.jl,  https://github.com/JuliaMath/Interpolations.jl/pull/56, three years ago. There was no discussion about it.

Alright, I'll take the carrot of warning-free code and make a PR for `missing` support when I get a chance.

**Comment by tomasaschan** [comment]
Just as a side note: the rationale for that warning as I remember it (even though it was probably never discussed as such in the issues here) was that we were getting questions, repeatedly, about why this library was performing badly, and it often turned out that the problems were arrays with missing values (or, specifically, arrays of non-leaf types). Because performance was one of the main motivators for creating the package in the first place (instead of e.g. building on its predecessor, Grid.jl), giving an automated hint about this to the user made sense at the time - it helped users to be effective in how they used the library, and it unburdened us maintainers from answering the same recurring questions.

Given that the landscape has changed, that warning is apparently obsolete, so removing or rewording it is a good idea.
