### ISSUE TITLE
Lanczos Resampling

### ISSUE THREAD

**Issue by mileslucas** [JuliaMath/Interpolations.jl#366]
I'm interested in implementing a Lanczos resampling algorithm here. This appears to be simply the convolution of the [Lanczos Kernel](https://en.wikipedia.org/wiki/Lanczos_resampling) by the samples.

I created a fork and started developing, but I have become completely overwhelmed by the complexity inside the library. I have no idea if such an interpolator should be its own interpolation type, or if it should be a `Gridded` type. I also have no clue how to interface with, well, anything here.

Can i get some advice on how/where to implement this algorithm (and whether you want it at all!)?

**Comment by MatFi** [comment]
First of all I don't now much about the internals, but after consulting the [DevDocs](https://juliamath.github.io/Interpolations.jl/previews/PR365/devdocs/) (part of https://github.com/JuliaMath/Interpolations.jl/pull/365) I think that it's not easy to do this with the ```Gridded``` directly, because it somehow built to work with polynomials rather then with convolutions. 
In terms of implementation it's probably a use case for FFT, at least when the window gets large (which is difficult in case of non-equidistant data). And actually it would be good to have some ```ConvolutionInterpolation```, where you can define arbitrary window functions. But again, I'am not an expert regarding this package (which is looking for a new maintainer https://github.com/JuliaMath/Interpolations.jl/pull/365)
