### ISSUE TITLE
Interpolation with -Inf givs NaN

### ISSUE THREAD

**Issue by eirikbrandsaas** [JuliaMath/Interpolations.jl#459]
Maybe it's intended, but it doesn't seem right to me (or at least it threw my code for a spin!)

```Julia
xs = [1,2,3] # grid
A = [-Inf,0,1] # Some weird array/function with Inf
interp_linear = LinearInterpolation(xs, A)
```
Where the last line gives `[-Inf,NaN,1]` while I expected `[-Inf,-Inf,1]` or something. The actually interpolated values are also surprising to me:
```Julia
julia> interp_linear(1.9)
-Inf

julia> interp_linear(2.0)
NaN

julia> interp_linear(2.1)
0.10000000000000009
```

However, this works:
```Julia
A = [nextfloat(-Inf),0,1] # Some weird array/function with largest negative number that is not -Inf
interp_linear = LinearInterpolation(xs, A)
```

**Comment by mkitti** [comment]
Could you justify your expectations?

**Comment by eirikbrandsaas** [comment]
Hah, putting me on the spot!

So, I don't understand why it's suddenly NaN at the next gridpoint. Either 0.0 or -Inf would make sense, but not NaN?

**Comment by mkitti** [comment]
My sense is that what you trying to accomplish is actually an extrapolation mode on the left side on the interval rather than actually trying to interpolate between `-Inf` and `0.0` on the interval [1,2]. Rather than encode this as an interpolation, I would consider doing this as an extrapolation.

```julia
julia> etp = LinearInterpolation([2,3],[0, 1]; extrapolation_bc=-Inf)
2-element extrapolate(interpolate((::Vector{Int64},), ::Vector{Int64}, Gridded(Linear())), -Inf) with element type Float64:
 Ratios.SimpleRatio{Int64}(0, 1)
 Ratios.SimpleRatio{Int64}(1, 1)

julia> etp(1)
-Inf

julia> etp(1.9)
-Inf

julia> etp(2.0)
0.0
```

A goal of this package is performance, so we're trying very hard not to introduce unneeded branches into the interpolation calculation. Thus, if we had to introduce a branch, it would be in the construction. If I had to make a choice to match MATLAB's output, I would either:
1. Convert any non-finite values to finite values
2. Insert an additional knot here at `prevfloat(2.0)`.

```julia
julia> etp = LinearInterpolation([1,prevfloat(2.),2,3],[-Inf,0,0,1])
4-element extrapolate(interpolate((::Vector{Float64},), ::Vector{Float64}, Gridded(Linear())), Throw()) with element type Float64:
 -Inf
 NaN
   0.0
   1.0

julia> etp(1)
-Inf

julia> etp(1.9)
-Inf

julia> etp(2.0)
0.0
```

**Comment by eirikbrandsaas** [comment]
> A goal of this package is performance
Sounds good to me, and that makes sense.

I can't do the extrapolation method since I need "real" extrapolation on the right. And it's not really extrapolation either, there are regions of my state space where the vector takes on -Inf values. The additional know method could work though. Thanks a lot for your helpful answers!

Closing this issue.
